[env:4d_systems_esp32s3_gen4_r8n16]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
monitor_speed = 115200
upload_speed = 460800

; Custom partition table for 16MB flash with large LittleFS
board_build.partitions = partitions_custom_16mb.csv
board_build.filesystem = littlefs

build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DCORE_DEBUG_LEVEL=3

lib_ldf_mode = deep+

lib_deps =
    adafruit/RTClib
    knolleary/PubSubClient@^2.8
    tzapu/WiFiManager@^2.0.17
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    ; ESP32 Async Web Server libraries
    esphome/ESPAsyncWebServer-esphome@^3.1.0
    esphome/AsyncTCP-esphome@^2.1.3
    bblanchon/ArduinoJson@^6.21.3